[package]
name = "go-sonar"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }
sha2 = "0.10"

[dependencies]
tauri = { version = "2", features = [] }
sonar-core = { path = "../crates/sonar-core" }
serde.workspace = true
serde_json.workspace = true
